package com.pjem.emprestimo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;
import org.hibernate.Hibernate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotEmpty;
import java.util.Date;
import java.util.Objects;


@Getter
@Setter
@ToString
@RequiredArgsConstructor
@Entity
//@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName ="TB_Emprestimo2")

public class Emprestimo {
    @DynamoDBHashKey
    @Column(name = "email", nullable = false)
    private String email;

    @NotEmpty
    //@DynamoDBAutoGeneratedKey
    private String codigo;

    @NotEmpty
    @DynamoDBAttribute(attributeName = "valoremprestimo")
    private float valoremprestimo;

    @NotEmpty
    @DynamoDBAttribute(attributeName = "datainicio")
    private Date datainicio;

    @NotEmpty
    @DynamoDBAttribute(attributeName = "numparcelas")
    private int numparcelas;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
        Emprestimo that = (Emprestimo) o;
        return email != null && Objects.equals(email, that.email);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}